<?php

$relativePath = __DIR__ . "/../Enums/GeneroEnum.php";
require_once $relativePath;

class Filme extends Titulo
{


    public function __construct
    (
        string $nome,
        int $anoLancamento,
         GeneroEnum $genero,
        public readonly  int $duracaoEmMinutos,

    )
    {
        parent::__construct($nome, $anoLancamento, $genero);

    }

    public function calculoDeMedia($notas): float
    {
        return parent::calculoDeMedia($notas); // TODO: Change the autogenerated stub
    }

    public function avaliarTitulo($notas)
    {
        parent::avaliarTitulo($notas);
    }

    public function calcularDuracaoCompleta(): int
    {
        return $this->duracaoEmMinutos;
    }


}